BAHT = 10
Dollar = 31.30
Yen = 3.54
Won = 35.59
BahtTODollar = BAHT/Dollar
BahtTOYen = BAHT*Yen
BahtTOWon = BAHT*Won
print(BAHT,'Baht =',BahtTODollar,'Dollar')
print(BAHT,'Baht =',BahtTOYen,'Yen')
print(BAHT,'Baht =',BahtTOWon,'Won')